apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-lab-pvc
  namespace: devops-lab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-storage
  resources:
    requests:
      storage: 10Gi
