apiVersion: v1
kind: Service
metadata:
  name: devops-lab-service
  namespace: default
  labels:
    app: devops-lab
spec:
  type: LoadBalancer
  selector:
    app: devops-lab
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
